# Generated by Beeline — do not edit by hand
# Template version: dev — app: hello-beeline
# Changes here are overwritten the next time Beeline updates this repository.
# syntax=docker/dockerfile:1

FROM node:24-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci

FROM node:24-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# Generates the Prisma client when the app uses one; a no-op otherwise.
RUN if [ -f prisma/schema.prisma ] || [ -d prisma/schema ]; then npx prisma generate; fi
RUN npm run build

FROM node:24-alpine AS runner
WORKDIR /app

RUN addgroup -S nodejs \
  && adduser -S nextjs -G nodejs

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Deliberately not Next.js standalone output: that needs `output: "standalone"`
# in next.config, which onboarding does not require and does not check. This
# runs `next start` against a full install, which works for any compliant repo.
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.* ./

USER nextjs
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=3s --start-period=20s --retries=3 \
  CMD wget -qO- http://127.0.0.1:3000/healthz || exit 1

CMD ["npm", "start"]
